name: Build and test Go code
on:
  push:
    branches:
      - master
      - 'test_*'
      - 'test-*'
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v1
    - name: Read Go versions
      run: echo "##[set-output name=go_version;]$(cat .github/versions/go)"
      id: go_versions
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ steps.go_versions.outputs.go_version }}
      id: go
    - name: Run tests
      run: |
        go test -race ./...
