name: Go
on:
  push:
    branches:    
      - master
      - 'test_*'
      - 'test-*'
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Read Go versions
      run: echo "##[set-output go_versions;]$(cat .github/versions/go)"
      id: go_versions
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ steps.go_versions.outputs.go_versions }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install test dependencies
      run: |
        go test -mod=vendor -i -race . ./tls110 ./gzip

    - name: Run tests
      run: |
        go test -mod=vendor -race . ./tls110 ./gzip
